import os
os.system('cls')

import turtle as t
def rekrusifSquare(line,level):
    if level == 0 :
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
    else :
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line)
        t.right(90)
        t.forward(line/2)
        t.right(90)
        t.forward(line/2)
        t.right(180)
        rekrusifSquare(line/2 , level-1) 
t.speed(6)    
rekrusifSquare(200 , 5)
t.done()